version: '3.3'
services:

  db:
    image: mysql:latest
    container_name: komodo-db
    restart: always
    env_file: 
      - ./.env
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./:/home
